In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
requests = __import__('requests')

# Define the API URL
url = "https://air-quality-api.open-meteo.com/v1/air-quality?latitude=23.81&longitude=90.41&hourly=pm2_5,pm10&past_days=90&timezone=Asia/Dhaka"

# Fetch data from the API
response = requests.get(url)
data = response.json()

# Extract hourly data
hourly_data = data["hourly"]

# Convert into a pandas DataFrame for analysis
df = pd.DataFrame({
    'time': hourly_data['time'],
    'pm2_5': hourly_data['pm2_5'],
    'pm10': hourly_data['pm10']
})

# Convert time column to datetime
df['time'] = pd.to_datetime(df['time'])

In [3]:
df.head()

                 time  pm2_5  pm10
0 2026-07-06 00:00:00    7.9   8.4
1 2026-07-06 01:00:00    7.6   8.1
2 2026-07-06 02:00:00    7.3   8.0
3 2026-07-06 03:00:00    6.5   7.2
4 2026-07-06 04:00:00    5.4   5.8

In [4]:
df.info

<bound method DataFrame.info of                     time  pm2_5  pm10
0    2026-07-06 00:00:00    7.9   8.4
1    2026-07-06 01:00:00    7.6   8.1
2    2026-07-06 02:00:00    7.3   8.0
3    2026-07-06 03:00:00    6.5   7.2
4    2026-07-06 04:00:00    5.4   5.8
...                  ...    ...   ...
2275 2026-10-08 19:00:00    NaN   NaN
2276 2026-10-08 20:00:00    NaN   NaN
2277 2026-10-08 21:00:00    NaN   NaN
2278 2026-10-08 22:00:00    NaN   NaN
2279 2026-10-08 23:00:00    NaN   NaN

[2280 rows x 3 columns]>

In [5]:
df.tail(20)

                    time  pm2_5  pm10
2260 2026-10-08 04:00:00   50.6  52.0
2261 2026-10-08 05:00:00   52.0  53.3
2262 2026-10-08 06:00:00   53.9  55.1
2263 2026-10-08 07:00:00    NaN   NaN
2264 2026-10-08 08:00:00    NaN   NaN
2265 2026-10-08 09:00:00    NaN   NaN
2266 2026-10-08 10:00:00    NaN   NaN
2267 2026-10-08 11:00:00    NaN   NaN
2268 2026-10-08 12:00:00    NaN   NaN
2269 2026-10-08 13:00:00    NaN   NaN
2270 2026-10-08 14:00:00    NaN   NaN
2271 2026-10-08 15:00:00    NaN   NaN
2272 2026-10-08 16:00:00    NaN   NaN
2273 2026-10-08 17:00:00    NaN   NaN
2274 2026-10-08 18:00:00    NaN   NaN
2275 2026-10-08 19:00:00    NaN   NaN
2276 2026-10-08 20:00:00    NaN   NaN
2277 2026-10-08 21:00:00    NaN   NaN
2278 2026-10-08 22:00:00    NaN   NaN
2279 2026-10-08 23:00:00    NaN   NaN

In [6]:
print(df['time'].dtype)

datetime64[us]

In [7]:
df['time']=pd.to_datetime(df['time'], errors='coerce')

In [8]:
print(df['time'].dtype)

datetime64[us]

In [9]:
df=df.set_index('time')

In [10]:
print(df.index)

DatetimeIndex(['2026-07-06 00:00:00', '2026-07-06 01:00:00',
               '2026-07-06 02:00:00', '2026-07-06 03:00:00',
               '2026-07-06 04:00:00', '2026-07-06 05:00:00',
               '2026-07-06 06:00:00', '2026-07-06 07:00:00',
               '2026-07-06 08:00:00', '2026-07-06 09:00:00',
               ...
               '2026-10-08 14:00:00', '2026-10-08 15:00:00',
               '2026-10-08 16:00:00', '2026-10-08 17:00:00',
               '2026-10-08 18:00:00', '2026-10-08 19:00:00',
               '2026-10-08 20:00:00', '2026-10-08 21:00:00',
               '2026-10-08 22:00:00', '2026-10-08 23:00:00'],
              dtype='datetime64[us]', name='time', length=2280, freq=None)